// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using ReportingModuleServer.Infrastructure.DataAccess.Sql.Entities;

namespace ReportingModuleServer.Infrastructure.DataAccess.Sql.Context;

public partial class ReportsContext : DbContext
{
    public ReportsContext(DbContextOptions<ReportsContext> options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Cyrillic_General_CI_AS");
        modelBuilder.HasSequence("seqPaymentNumber", "Payments").StartsAt(6000L);

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}