// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace ReportingModuleServer.Infrastructure.DataAccess.Sql.Entities
{
    public partial class uspGetContractRentAndFeesReportSourceResult
    {
        public Guid RentItemId { get; set; }
        public Guid ProjectId { get; set; }
        [StringLength(30)]
        public string? Project { get; set; }
        [StringLength(30)]
        public string Building { get; set; } = default!;
        public Guid? BuildingGuid { get; set; }
        [StringLength(30)]
        public string PropertyUnit { get; set; } = default!;
        [StringLength(50)]
        public string ClassName { get; set; } = default!;
        [Column("Tenant/Recipient")]
        [StringLength(201)]
        public string? TenantRecipient { get; set; }
        [StringLength(50)]
        public string? ContractName { get; set; }
        public DateOnly ChargeMonth { get; set; }
        public double? RentArea { get; set; }
        [Column("Rent", TypeName = "decimal(38,2)")]
        public decimal? Rent { get; set; }
        [Column("ManagementFee", TypeName = "decimal(38,2)")]
        public decimal? ManagementFee { get; set; }
    }
}
